# This automatically compiles the code when merges are made to main. 
# It may eventually be integrated with JUnit5 testing. 
# For now it just shows issues in compiling the codebase

image: eclipse-temurin:11

stages:          # List of stages for jobs, and their order of execution
  - build
  - test

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Compiling the code..."
    - javac -sourcepath ./src -d ./bin/ ./src/main/Main.java
    - echo "Compiling test code..."
    - javac -cp ./JARs/junit-jupiter-5.10.0.jar -cp ./JARs/junit-platform-console-standalone-1.10.2.jar -sourcepath ./src -d ./testBin/ ./test/main/*
    - echo "Compile complete."

JUnit-tests:
  stage: test
  script:
  - echo "Running Tests..."
  - pwd
  - java -jar ./JARs/junit-platform-console-standalone-1.10.2.jar execute --class-path ./testBin/ --scan-class-path --reports-dir ./reports
  - echo "Tests complete."

  artifacts:
    reports:
      junit: ./reports/*jupiter.xml
